# Generated by Django 3.0.2 on 2021-03-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectlist', models.CharField(max_length=30, verbose_name='科目一覧')),
            ],
        ),
        migrations.CreateModel(
            name='Studylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=500, verbose_name='問題')),
                ('answer', models.CharField(max_length=500, verbose_name='答え')),
                ('detail', models.TextField(default='ここに解説を入力してください', max_length=1000, verbose_name='詳しい説明')),
                ('subjectlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.SubjectList', verbose_name='科目')),
            ],
        ),
    ]
